### ISSUE TITLE
Support for Scala 2.10

### ISSUE THREAD

**Issue by ncreep** [xdotai/diff#9]
Hi,

Any chance for publishing a Scala 2.10 build of this library?

Thanks

**Comment by cvogt** [comment]
I'll give it a shot.

**Comment by cvogt** [comment]
fixed. instructions in the readme. don't forget to add the paradise plugin to your build, when you use it.

**Comment by cvogt** [comment]
the artifacts are on sonatype and should show up on maven central as soon as they are synced

**Comment by ncreep** [comment]
Thanks for the quick response, this is much appreciated.

**Comment by cvogt** [comment]
You are welcome. Gave me a good reason to test cross version publishing with CBT. It leads to me fixing a bug, trying compiler plugins with CBT and adding a macro paradise plugin for CBT :).

**Comment by ylaurent** [comment]
I'm using scala 2.10 with maven, I added you dependencies and configured the scala-maven plugin like that:

```
<build>
    <plugins>
      <plugin>
        <groupId>net.alchim31.maven</groupId>
        <artifactId>scala-maven-plugin</artifactId>
        <configuration>
          <compilerPlugins>
            <compilerPlugin>
              <groupId>org.scalamacros</groupId>
              <artifactId>paradise_${scala.version}</artifactId>
              <version>2.1.0-M5</version>
            </compilerPlugin>
          </compilerPlugins>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.scalatest</groupId>
        <artifactId>scalatest-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
```

but when i try your sample code from README i get:
Cannot find DiffShow[Foo] to diff values (Foo(Bar(asdf,5),List(123, 1234),Some(Bar(asdf,5))), Foo(Bar(asdf,66),List(1234),Some(Bar(qwer,5))))
Any idea ? Do that mean that the compilerPlugin isn't working ?
